from network import NetworkError

class AuthError(NetworkError):
    pass